--
-- Create table bid
--
CREATE TABLE bids (
	id			BIGINT			AUTO_INCREMENT(1,1),
	name		VARCHAR2(255)	NOT NULL,
	price		DOUBLE					,
);
CREATE INDEX IDX_BID_NAME ON BIDS(NAME);
-- ALTER TABLE BIDS CONSTRAINT BIDS_PK_ID PRIMARY KEY (ID);
